name: tests

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    moonshine-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  tools: composer:v2
                  coverage: none
            - uses: actions/checkout@v4

            - name: Set up MySQL
              env:
                  DB_USERNAME: root
                  DB_PASSWORD: 12345
                  DB_DATABASE: my_database_test
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}

            - name: Create .env.testing
              run: |
                  echo "APP_NAME=App" > .env.testing
                  echo "APP_ENV=testing" >> .env.testing
                  echo "APP_KEY=base64:XCPrsF+U8VYa6qN0halPXgOGDkJjgrJJlyxirgiGXQ0=" >> .env.testing
                  echo "APP_DEBUG=true" >> .env.testing
                  echo "APP_TIMEZONE=UTC" >> .env.testing
                  echo "APP_URL=http://localhost" >> .env.testing
                  
                  echo "DB_CONNECTION=mysql" >> .env.testing
                  echo "DB_HOST=localhost" >> .env.testing
                  echo "DB_PORT=3306" >> .env.testing
                  echo "DB_DATABASE=my_database_test" >> .env.testing
                  echo "DB_USERNAME=root" >> .env.testing
                  echo "DB_PASSWORD=12345" >> .env.testing

            - name: Install Dependencies
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            - name: Run tests
              run: vendor/bin/phpunit
